version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb-yacht
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGODB_DATABASE: test
    ports:
      - 27019:27017
    volumes:
      - '/data/db'

volumes:
  mongodb_data:
    driver: local
